#!/bin/sh /etc/rc.common

START=18

USE_PROCD=1
PROG=/usr/share/ubispotfilter/ubispotfilter.uc
PIDFILE=/var/run/ubispotfilter.pid

start_service() {
	logger -t ubispot "Starting ubispotfilter service"
	procd_open_instance
	procd_set_param command "$PROG"
	procd_set_param respawn
	procd_set_param pidfile "$PIDFILE"
	procd_close_instance

	local pid
	for i in $(seq 1 5); do
		if [ -f "$PIDFILE" ]; then
			pid=$(cat "$PIDFILE")
			logger -t ubispotfilter "ubispotfilter service started with PID $pid"
			break
		elif pid=$(pidof ubispotfilter); then
			logger -t ubispotfilter "ubispotfilter service started with PID $pid"
			break
		fi
		sleep 1
	done
	[ -z "$pid" ] && logger -t ubispotfilter "Could not determine ubispotfilter PID after 5 seconds"
}
