#!/bin/sh /etc/rc.common

START=80

USE_PROCD=1
PROG=/usr/share/ubispot/ubispot.uc
DAS_PROG=/usr/bin/ubispot-das
PIDFILE=/var/run/ubispot.pid

launch_das() {
	local ubispot="$1"

	procd_open_instance "$ubispot"
	procd_set_param command "$DAS_PROG" -u "$ubispot"
	procd_set_param respawn
	procd_close_instance
}

add_das() {
	local cfg="$1"
	local das_secret

	config_get das_secret "$cfg" "das_secret" "0"
	[ "$das_secret" = "0" ] || launch_das "$cfg"
}

start_service() {
	logger -t ubispot "Starting ubispot service"
	procd_open_instance
	procd_set_param command "$PROG"
	procd_set_param respawn
	procd_set_param pidfile "$PIDFILE"
	procd_close_instance

	local pid
	for i in $(seq 1 5); do
		if [ -f "$PIDFILE" ]; then
			pid=$(cat "$PIDFILE")
			logger -t ubispot "ubispot service started with PID $pid"
			break
		elif pid=$(pidof ubispot); then
			logger -t ubispot "ubispot service started with PID $pid"
			break
		fi
		sleep 1
	done
	[ -z "$pid" ] && logger -t ubispot "Could not determine ubispot PID after 5 seconds"
	
	config_load ubispot
	config_foreach add_das ubispot
}
