#!/bin/sh /etc/rc.common

START=18

USE_PROCD=1
PROG=/usr/share/uspotfilter/uspotfilter.uc
PIDFILE=/var/run/uspotfilter.pid

start_service() {
	logger -t uspot "Starting uspotfilter service"
	procd_open_instance
	procd_set_param command "$PROG"
	procd_set_param respawn
	procd_set_param pidfile "$PIDFILE"
	procd_close_instance

	local pid
	for i in $(seq 1 5); do
		if [ -f "$PIDFILE" ]; then
			pid=$(cat "$PIDFILE")
			logger -t uspotfilter "uspotfilter service started with PID $pid"
			break
		elif pid=$(pidof uspotfilter); then
			logger -t uspotfilter "uspotfilter service started with PID $pid"
			break
		fi
		sleep 1
	done
	[ -z "$pid" ] && logger -t uspotfilter "Could not determine uspotfilter PID after 5 seconds"
}
